spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpashop
    username: root
    password: 4316
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true;
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
